name: Send Slack notification on activity
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
  watch:
    types: [started]
  fork:
    types: [created]
  repository_dispatch:
    types: [starred]
jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.23.0
env:
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
