name: Send Slack notification on activity
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
  watch:
    types: [started]
  fork:
    types: [created]
  repository_dispatch:
    types: [starred]
jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.23.0
        with: 
          # For posting a rich message using Block Kit
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":red_circle: New ${{ github.event_name }}",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Created by *${{ github.event.sender.login }}*"
                  }
                }
              ]
            }
env:
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
